[theme]
primaryColor = "#0284c7"
backgroundColor = "#0b0f19"
secondaryBackgroundColor = "#111827"
textColor = "#f3f4f6"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
